version: 2

sources:
  - name: dagster
    description: Raw data assets managed by Dagster Python assets
    schema: public
    tables:
      - name: uac_applicants_by_age
        description: Age distribution of UAC Early Bird applicants (Year 12 vs Non-Year 12)
        meta:
          dagster:
            asset_key: ["uac_applicants_by_age"]
      - name: uac_applicants_by_gender
        description: Gender split of UAC Early Bird applicants
        meta:
          dagster:
            asset_key: ["uac_applicants_by_gender"]
      - name: uac_early_bird_closing_count
        description: Historical UAC Early Bird applicant volumes by year
        meta:
          dagster:
            asset_key: ["uac_early_bird_closing_count"]
      - name: uac_fos_by_gender
        description: UAC field of study preferences by gender
        meta:
          dagster:
            asset_key: ["uac_fos_by_gender"]
      - name: uac_fos_by_app_type
        description: UAC field of study preferences by applicant type
        meta:
          dagster:
            asset_key: ["uac_fos_by_app_type"]
      - name: job_market
        description: IVI job vacancies by ANZSCO skill level and state
        meta:
          dagster:
            asset_key: ["job_market"]
      - name: job_market_occupations
        description: IVI job vacancies by ANZSCO2 occupation group and state
        meta:
          dagster:
            asset_key: ["job_market_occupations"]
      - name: occupation_fos_mapping
        description: Manual mapping of ANZSCO2 occupations to UAC fields of study
        meta:
          dagster:
            asset_key: ["occupation_fos_mapping"]
      - name: abs_population_by_lga
        description: ABS estimated resident population (15-19 year olds) by LGA
        meta:
          dagster:
            asset_key: ["abs_population_by_lga"]
      - name: abs_lga_reference
        description: ABS LGA reference data — names, state mapping, and land area (2024 boundaries)
        meta:
          dagster:
            asset_key: ["abs_lga_reference"]
      - name: google_trends
        description: Current trending Google searches in Australia
        meta:
          dagster:
            asset_key: ["google_trends"]
      - name: qilt_graduate_outcomes
        description: QILT Graduate Outcomes Survey — employment rates and salaries by study area
        meta:
          dagster:
            asset_key: ["qilt_graduate_outcomes"]
      - name: qilt_student_experience
        description: QILT Student Experience Survey — satisfaction indicators by study area
        meta:
          dagster:
            asset_key: ["qilt_student_experience"]
      - name: qilt_institution_scores
        description: QILT institution scorecard — satisfaction, employment, and salary per university
        meta:
          dagster:
            asset_key: ["qilt_institution_scores"]
      - name: cricos_courses
        description: >
          CRICOS higher-education course listings — denormalized from institutions,
          courses, locations, and course-locations CSVs. Covers ~9,000+ courses
          across all providers registered for international students.
        meta:
          dagster:
            asset_key: ["cricos_courses"]
      - name: google_trends_interest
        description: >
          Google Trends search interest over time for 42 Australian university names.
          Monthly granularity over a 5-year rolling window. Cross-batch normalized
          so interest values (0-100) are comparable across all universities.
        meta:
          dagster:
            asset_key: ["google_trends_interest"]
      - name: google_trends_interest_by_state
        description: >
          Google Trends state-level search interest for 42 Australian university names.
          Relative interest (0-100) per state/territory, cross-batch normalized.
          Single snapshot representing ~5-year aggregate geographic search patterns.
        meta:
          dagster:
            asset_key: ["google_trends_interest_by_state"]
      - name: google_trends_related_queries
        description: >
          Google Trends related queries (top and rising) for 42 Australian
          university names. Rising values show growth % or "Breakout".
        meta:
          dagster:
            asset_key: ["google_trends_related_queries"]
      - name: vtac_fos_preferences
        description: >
          VTAC field-of-study first preferences by gender (Victorian applicants).
          Parsed from VTAC annual statistics Section D (Table D1). ASCED broad
          field classification with gender breakdown.
        meta:
          dagster:
            asset_key: ["vtac_fos_preferences"]
      - name: satac_fos_preferences
        description: >
          SATAC field-of-study first preferences by gender (SA/NT domestic
          applicants). Parsed from SATAC annual statistics PDF. ASCED broad
          field classification with gender breakdown. Year 12 + Non-Year 12
          summed for domestic totals.
        meta:
          dagster:
            asset_key: ["satac_fos_preferences"]
