zeus_market_research:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_DATABASE', '/home/dave/project-zeus-market-research/analytics/analytics.duckdb') }}"
      schema: marts
      threads: 1
