zeus_market_research_uk:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_DATABASE', '/home/dave/project-zeus-market-research/projects/analytics-uk/analytics.duckdb') }}"
      schema: marts
      threads: 1
