version: 2

models:
  - name: opportunity_gap
    description: >
      Opportunity gap analysis comparing job vacancy demand (from IVI data) against
      student preference share (from UAC Early Bird data) by field of study.
      A positive gap means more job demand than student interest — the strongest
      messaging opportunities for university marketing campaigns.
    columns:
      - name: field_of_study
        description: UAC field of study category (e.g. Health, Engineering & Related Technologies)
        tests:
          - unique
          - not_null
      - name: total_vacancies
        description: Total internet job vacancies across all mapped ANZSCO2 occupations for this field
      - name: vacancy_share
        description: This field's share of total mapped vacancies (0-1 decimal)
      - name: preference_share
        description: Share of UAC Early Bird first preferences for this field (0-1 decimal)
      - name: opportunity_gap
        description: >
          vacancy_share minus preference_share. Positive values indicate fields where
          job demand exceeds student interest — prime targets for marketing messaging.
      - name: vacancy_growth_12m
        description: >
          12-month growth rate of vacancies for this field's mapped occupations.
          Computed as (current - prior) / prior. Null when prior-year data is unavailable.
      - name: opportunity_rank
        description: Rank by opportunity_gap descending (1 = largest gap)
        tests:
          - unique
          - not_null

  - name: opportunity_gap_by_gender
    description: >
      Extends the opportunity gap analysis with gender preference breakdowns.
      Shows which high-gap fields skew male or female, enabling gender-targeted
      ad creative and audience segmentation for university marketing campaigns.
    columns:
      - name: field_of_study
        description: UAC field of study category
        tests:
          - unique
          - not_null
      - name: opportunity_gap
        description: Vacancy share minus preference share (from opportunity_gap mart)
      - name: opportunity_rank
        description: Rank by opportunity_gap descending (1 = largest gap)
      - name: vacancy_share
        description: This field's share of total mapped vacancies (0-1 decimal)
      - name: vacancy_growth_12m
        description: 12-month growth rate of vacancies for this field's mapped occupations
      - name: female_preference_share
        description: Share of female UAC Early Bird first preferences for this field (0-1 decimal)
      - name: male_preference_share
        description: Share of male UAC Early Bird first preferences for this field (0-1 decimal)
      - name: gender_skew
        description: >
          female_preference_share minus male_preference_share. Positive values
          indicate female-skewing fields, negative values indicate male-skewing.
      - name: skew_direction
        description: Which gender has higher preference share (Female, Male, or Balanced)

  - name: state_demand_index
    description: >
      State-level demand index comparing graduate-relevant job vacancies (ANZSCO
      skill levels 1-2) against youth population (15-19 year olds) by state.
      Identifies geographic hotspots where job demand outpaces the youth talent pool —
      signals where to concentrate university marketing spend.
    columns:
      - name: state
        description: Australian state/territory code (NSW, VIC, QLD, SA, WA, TAS, NT, ACT)
        tests:
          - unique
          - not_null
      - name: graduate_vacancies
        description: Latest-month job vacancies at ANZSCO skill levels 1-2 (bachelor degree or diploma level)
      - name: total_vacancies
        description: Latest-month total job vacancies across all skill levels
      - name: youth_population_15_19
        description: ABS estimated resident population aged 15-19 (latest available year)
      - name: graduate_vacancies_per_1k_youth
        description: >
          Graduate-level vacancies per 1,000 youth (15-19). Higher values indicate
          states where graduate job demand is strongest relative to the youth pipeline.
      - name: total_vacancies_per_1k_youth
        description: Total vacancies per 1,000 youth (15-19)
      - name: graduate_share_of_vacancies
        description: Proportion of vacancies that are graduate-level (skill 1-2) in this state
      - name: graduate_vacancy_growth_12m
        description: 12-month growth rate of graduate-level vacancies
      - name: total_vacancy_growth_12m
        description: 12-month growth rate of total vacancies
      - name: demand_rank
        description: Rank by graduate_vacancies_per_1k_youth descending (1 = highest demand density)
        tests:
          - unique
          - not_null

  - name: audience_profile_by_fos
    description: >
      Audience targeting profile for each UAC field of study. Combines gender
      preference splits, mature learner affinity (Non-Year 12 over-indexing),
      and geographic origin signals (interstate draw) with opportunity gap context.
      Answers "who should we target and where are they?" for each field.
    columns:
      - name: field_of_study
        description: UAC field of study category
        tests:
          - unique
          - not_null
      - name: opportunity_gap
        description: Vacancy share minus preference share (null for unmapped fields)
      - name: opportunity_rank
        description: Rank by opportunity gap (null for unmapped fields)
      - name: vacancy_share
        description: This field's share of total mapped vacancies
      - name: female_preference_share
        description: Share of female applicants preferring this field
      - name: male_preference_share
        description: Share of male applicants preferring this field
      - name: gender_skew
        description: Which gender over-indexes on this field (Female, Male, or Balanced)
      - name: non_yr12_preference_share
        description: Share of Non-Year 12 (mature age) applicants preferring this field
      - name: total_preference_share
        description: Share of all applicants preferring this field
      - name: mature_learner_index
        description: >
          Non-Year 12 share divided by Total share. Values above 1.0 indicate
          the field attracts disproportionately more mature-age applicants.
      - name: nsw_preference_share
        description: Share of NSW Year 12 applicants preferring this field
      - name: act_preference_share
        description: Share of ACT Year 12 applicants preferring this field
      - name: interstate_preference_share
        description: Share of Interstate & IB Year 12 applicants preferring this field
      - name: interstate_draw_ratio
        description: >
          Interstate share divided by NSW share. Values above 1.0 indicate the
          field draws disproportionately from interstate — a signal for national campaigns.

  - name: trending_interests
    description: >
      Current Google trending searches in Australia enriched with best-effort
      field of study classification and opportunity gap context. Refreshes each
      time the google_trends asset is materialized. Helps marketers identify
      timely messaging hooks that align with high-opportunity fields.
    columns:
      - name: trend
        description: The trending search term
        tests:
          - not_null
      - name: traffic
        description: Approximate search traffic volume (e.g. "200+", "1000+", "2000+")
      - name: published
        description: When the trend was published to Google Trends RSS
      - name: top_article_headline
        description: Headline of the top news article associated with this trend
      - name: top_article_source
        description: News source of the top article
      - name: top_article_url
        description: URL of the top article
      - name: explore_link
        description: Google Trends explore link for this search term
      - name: matched_field_of_study
        description: >
          Best-effort keyword match to a UAC field of study. Null when no match
          is found — most trends won't match and should be reviewed manually.
      - name: opportunity_gap
        description: Opportunity gap for the matched field (null if unmatched)
      - name: opportunity_rank
        description: Opportunity rank for the matched field (null if unmatched)
      - name: vacancy_growth_12m
        description: Vacancy growth for the matched field (null if unmatched)
      - name: marketing_signal
        description: >
          Actionable recommendation based on match and opportunity gap:
          "High opportunity" for positive-gap fields, "Low opportunity" for
          negative-gap fields, "Unclassified" for unmatched trends.
